redis:
  type: 'single'
  options:
      host: '117.72.69.39'
      port: 16379
      db: 0

user-service:
  host: localhost
  port: 3001


database:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: postgres
  password: '123'
  database: postgres
  synchronize: true
  logging: false
  entities: User
  autoLoadEntities: true
  retryAttempts: 5

#DATABASE_ENTITIES=entities/.*js,**/entities/.*js,**/entities/.*ts,modules/**/entities/.*js
